resources:
  - name: repo
    type: git
    source:
      uri: https://github.com/Fixater/concourse_test.git



jobs:
  - name: test
    plan:
    # Add a get step referencing the resource
      - get: repo
        trigger: true # tell Concourse to trigger this job when new versions are emitted
      - task: test-task
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: mesosphere/aws-cli
          inputs:
          - name: repo
          run:
            path: aws
            args: [ --version ]
            #path: echo
            #args: [ "Vault token =  ((packer.vault_access_token))" ]